### ISSUE TITLE
vtop is not painting correctly a special character

### ISSUE THREAD

**Issue by Josenzo** [zeit/hyperterm#224]

**Comment by aaronagray** [comment]
Ditto. This is how it looks for me.

<img width="1266" alt="screen shot 2016-07-18 at 12 14 13 pm" src="https://cloud.githubusercontent.com/assets/1110019/16925390/36011854-4ce1-11e6-975f-5427038f5348.png">

**Comment by aaronagray** [comment]
I wonder if there is an underlying UTF-8 issue. This seems like a similar problem described (and solved) in #246.

**Comment by MrRio** [comment]
Author of vtop here -- looks like we'll need to tweak something in hterm

**Comment by albinekb** [comment]
The issue seen here was fixed by adding the <meta> tag: https://github.com/zeit/hyperterm/commit/9c50fd5148443927496290811cc356a11f939a1a 
(released with the latest hyperterm `0.7.1`)

However, vtop is still not rendering correctly due to an issue with hterm and the width-calculation of characters. 
See issue: #46 and the fix-in-progress: #535
