### ISSUE TITLE
Unable to take screenshot of hyperterm

### ISSUE THREAD

**Issue by dbkaplun** [zeit/hyperterm#317]
I don't know why but it seems OSX does not register hyperterm in some way so when I try to take a screenshot with `Cmd+Shift+4` I only get a picture of what's behind the hyperterm window.

**Comment by insanityfarm** [comment]
I can't reproduce this. What plugins are you running?

**Comment by dfrankland** [comment]
If you are using [`hyperterm-transparent-bg`](https://github.com/dfrankland/hyperterm-transparent-bg/), this is a side-effect of that, because [it's necessary to capture the entire screen without the console shown](https://github.com/dfrankland/hyperterm-transparent-bg/blob/master/index.js#L40). Feel free to [raise an issue](https://github.com/dfrankland/hyperterm-transparent-bg/issues/new).

**Comment by dbkaplun** [comment]
Confirmed, disabling `hyperterm-transparent-bg` fixed the problem. Closing.
