### ISSUE TITLE
Unknown methods crash terminal

### ISSUE THREAD

**Issue by ShMcK** [zeit/hyperterm#374]
Unknown methods with a length of more than one cause HyperTerm to consistently crash.

```shell
a.b
> a.b: command not found

ab.a
> ab.a: command not found

a.ab
> CRASH

ab.ab
> CRASH
```

**Comment by ekmartin** [comment]
With crash, do you mean that the term turns into a black screen? If so, that's because Hyperterm thinks `ab.ab` is an URL and tries to open it in a webview (you can exit with CTRL+C).

It would probably be smart to listen to [did-fail-load](http://electron.atom.io/docs/api/web-view-tag/#event-did-fail-load) and display an error page whenever it happens though.

**Comment by ShMcK** [comment]
Yes, the screen goes black. I hadn't realized HyperTerm had a webview.
