### ISSUE TITLE
Feature request: make character under cursor visible

### ISSUE THREAD

**Issue by rafaelrinaldi** [zeit/hyperterm#425]
Right now it's impossible to know what character is under the cursor block if you don't memorize it. It would be nice to be able to do that.

**Comment by rauchg** [comment]
We just introduced opacity support: https://github.com/zeit/hyperterm/releases/tag/v0.7.0

**Comment by rafaelrinaldi** [comment]
@rauchg That does the job but it's not quite the solution I'm looking for. I want to have exactly the same behavior from Terminal.app + Vim.

Will give it a shot!

**Comment by jordwalke** [comment]
So is the opacity why when I type, I momentarily see the character under the cursor before the cursor moves forward? That felt weird to me so I thought it was a bug, and I came here to search for issues. Should the cursor move right immediately as a character is inserted so there is no opportunity for the two to overlap? (That's what it appears like in iTerm, but I don't know if it's just because there's no opacity support on their cursor).

**Comment by net** [comment]
Opacity is a poor solution @rauchg.

**Comment by mofux** [comment]
This might change if #1275 gets implemented. xterm.js provides a separate cursor element that contains the active character, which means a block style cursor can be styled using background and text color.

**Comment by rauchg** [comment]
@mofux that's likely the direction we're going
