### ISSUE TITLE
Gaze watch error: ENOENT

### ISSUE THREAD

**Issue by knownasilya** [zeit/hyperterm#444]
<img width="427" alt="screen shot 2016-07-26 at 6 39 59 pm" src="https://cloud.githubusercontent.com/assets/34726/17157878/76651780-5360-11e6-97bc-52e0cde75d60.png">

For some reason gaze was watching the contents of a command's directory, in this case `gcloud ..` and failed. The command kept running I think.

**Comment by albinekb** [comment]
Related: #225

**Comment by sveggiani** [comment]
Exact same thing is happening to me after upgrading to v0.7.1

**Comment by sveggiani** [comment]
I did a complete clean install and the problem persisted for me. I can't get it to work again since v0.7.1.

This is the error and the state of the main window after clicking ok.

![screen shot 2016-07-29 at 8 16 52 pm](https://cloud.githubusercontent.com/assets/560791/17265931/847d1488-55c9-11e6-85dd-ad49cf884dc6.png)
![screen shot 2016-07-29 at 8 17 11 pm](https://cloud.githubusercontent.com/assets/560791/17265932/84808398-55c9-11e6-8ad1-0f23842a067a.png)

**Comment by albinekb** [comment]
@sveggiani `ENOENT` error is basically "no such file or directory"
do you have fish installed at `/user/local/bin/fish`?

try setting `shell` in your `.hyperterm.js` => `shell: '/bin/bash'`

**Comment by sveggiani** [comment]
@albinekb you were right. I didn't noticed that the shell key was automatically added and set to ´usr/local/bin/fish´. Fish is installed and working there but doesn't seem to work with Hyperterm.

I've set ´/bin/bash´and ´bin/zsh`and works perfectly.

**Comment by matheuss** [comment]
Closing in favor of #225
