### ISSUE TITLE
Allow for config sync across machines

### ISSUE THREAD

**Issue by amdilley** [zeit/hyperterm#465]
I use HyperTerm at work and at home and would love to be able to sync my settings across devices. 

With other apps I have used Dropbox to store my config and then used symlinks to point to the config dir or file. Attempts to do so in HyperTerm haven't proven successful.

Hope to see the ability to specify the target directory for .hyperterm.js in future releases.

**Comment by ekmartin** [comment]
Creating a symlink from your Dropbox config file to `.hyperterm.js` should work, i.e. `ln -s /path/to/dropbox/hyperterm.config.js ~/.hyperterm.js`. The file basically looks the same to Hyperterm in the end after all. Or were you thinking of something else?

There's also [this](https://github.com/dfrankland/hyperterm-sync-settings) plugin by @dfrankland that syncs your settings to a Gist - if you'd rather do that (not sure if it's updated to 0.7.0+ though).

**Comment by amdilley** [comment]
Perfect. I found out that I had to quit then reopen HyperTerm after creating the symlink to get this to work.

**Comment by albinekb** [comment]
@amdilley 
Look at this: https://github.com/dfrankland/hyperterm-sync-settings

**Comment by thedonquixotic** [comment]
@ekmartin @albinekb I've tried to use symlinks to sync all my config files etc and it is not working. I think it might be because of the symlinks. Everytime I make a change to .hyper.js it will throw an error after saving saying it can't access the package.json file. 

I'm using WSL with bash and zsh installed. Bash and zsh are running fine, but I installed them fully before trying to install hyper etc. Hyper works when I don't symlink. And it works when I do symlink but once it's symlinked it will not work quite right because of the package.json error etc. 

I logged an issue for this here: https://github.com/zeit/hyper/issues/3132
