### ISSUE TITLE
Close icon failed to load, file not found

### ISSUE THREAD

**Issue by jbw91** [zeit/hyperterm#490]
![screen shot 2016-07-28 at 4 12 58 pm](https://cloud.githubusercontent.com/assets/5883616/17231314/67ece88e-54de-11e6-948d-171be267958f.png)

New installation of HyperTerm (v0.7.1.36) and there is no close icon for the tabs. All that is visible is a hard to see gray circle where it should be. Screenshot shows error of missing icon.

**Comment by c0b41** [comment]
already fixed 8874fef or not?

**Comment by ingorichter** [comment]
I don't think  that https://github.com/zeit/hyperterm/commit/8874feff7605d39d1de98546bc22b776b2673f51 fixes the issues for a release build. The icon needs to be part of the app bundle and there is not `dist` directory. Looks more like a packaging issue, since the `assets` folder is entirely missing from `HyperTerm.app/Contents/Resources/app/`

**Comment by leo** [comment]
Already fixed in https://github.com/zeit/hyperterm/commit/8874feff7605d39d1de98546bc22b776b2673f51 and https://github.com/zeit/hyperterm/commit/2a13f3a38f686131d479947e7a36e64ef1f2bd76.

**Comment by pakastin** [comment]
Right click menu would be nice also: "close tab", "close other tabs", ...
