### ISSUE TITLE
How to update hyperterm

### ISSUE THREAD

**Issue by ryangun** [zeit/hyperterm#548]
Sorry, I'm a beginner. How can I update hyperterm? Thank you!

**Comment by CodeTheory** [comment]
Hi there! What system are you on? OSX HyperTerm supports Automatic Updates and so you should see a notification from your HyperTerm window when there is an update available (so long as you're on a version that supports it. >4.x I believe.)

Also make sure that you aren't on the latest version of HyperTerm, otherwise there is no updates to update to.

If you're wondering how to take advantage of all the merges and updates to the repository, you can clone the repo and build the app yourself to have the latest features; but these aren't officially released yet and so may contain bugs.

If there's anything more you'd like to know, please feel free to ask! Alternatively, you can join the community channel at https://zeit.chat and ask the community there any questions you may have. 😄

**Comment by ryangun** [comment]
@CodeTheory Your patient andswer makes me surprised, It helps me a lot.

**Comment by CodeTheory** [comment]
I'm glad! I aim to assist. 😄

**Comment by jakubsvobodacz** [comment]
How can I disable automatic updates?

**Comment by juliankleine** [comment]
Why would you disable automatic updates?
