### ISSUE TITLE
Any way to move tab with keyboard shortcut?

### ISSUE THREAD

**Issue by mocheng** [zeit/hyperterm#625]
Switching tabs might not be enough. In some cases. user prefer to move tabs to re-organzie them.

I tried some plugins to enable moving tabs by dragging. However, the funny thing is that `CMD + ALT + left/right arrow` shortcut doesn't follow the visualized tab sequence, but still follow the sequence of tab creation.

**Comment by CodeTheory** [comment]
Hi there! Because moving tabs within HyperTerm isn't a feature yet, I wouldn't say this is necessarily an issue. However, since this seems to be a planned feature, I think this is totally valid input and invite you to suggest re-ordering tabs by command on the original issue for re-arranging tabs #39. 

Thanks for your input!

**Comment by patrik-piskay** [comment]
Hi @mocheng, please check [hyperterm-tabs](https://github.com/patrik-piskay/hyperterm-tabs) plugin, it recently got shortcut fix (left/right arrows as well as `cmd+1-9`) to follow the current order.
